CREATE TABLE workflow
(
    workflow_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    workflow_code VARCHAR(255),
    name          VARCHAR(255),
    description   VARCHAR(255),
    version       VARCHAR(255),
    status        SMALLINT,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_workflow PRIMARY KEY (workflow_id)
);